#define LEFT_MOTOR_POWER 3 // (enA)
#define LEFT_MOTOR_FORWARD 2 // (in1)
#define LEFT_MOTOR_BACKWARD 4 // (in2)
#define RIGHT_MOTOR_POWER 6 // (enB)
#define RIGHT_MOTOR_FORWARD 7 // (in3)
#define RIGHT_MOTOR_BACKWARD 5 // (in4)
#define LEFT_ENCODER 12
#define RIGHT_ENCODER 13
#define LEFT_ULTRASONIC_TRIG 8
#define LEFT_ULTRASONIC_ECHO 9
#define FRONT_ULTRASONIC_TRIG 11
#define FRONT_ULTRASONIC_ECHO 10
#define LEFT_INFRARED A4
#define RIGHT_INFRARED A5